#!/bin/sh

set -e

NAME=clash
PIDFILE=/var/run/$NAME.pid
DAEMON=/config/clash/clash
DAEMON_OPTS=" -d /config/clash"

PATH="${PATH:+$PATH:}/usr/sbin:/sbin"

. /lib/lsb/init-functions

case "$1" in
  start)
        echo -n "Starting daemon: "$NAME
    start-stop-daemon --start --quiet --make-pidfile -b --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_OPTS
        echo "."
    ;;
  stop)
        echo -n "Stopping daemon: "$NAME
    start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE
        echo "."
    ;;
  restart)
        echo -n "Restarting daemon: "$NAME
    start-stop-daemon --stop --quiet --oknodo --retry 30 --pidfile $PIDFILE
    start-stop-daemon --start --quiet --make-pidfile -b --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_OPTS
    echo "."
    ;;
  status)
    status_of_proc -p $PIDFILE $DAEMON $NAME
    ;;

  *)
    echo "Usage: "$1" {start|stop|restart|status}"
    exit 1
esac

exit 0